// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: endpoint.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Iroha.Protocol {

  /// <summary>Holder for reflection information generated from endpoint.proto</summary>
  public static partial class EndpointReflection {

    #region Descriptor
    /// <summary>File descriptor for endpoint.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EndpointReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lbmRwb2ludC5wcm90bxIOaXJvaGEucHJvdG9jb2waC2Jsb2NrLnByb3Rv",
            "Gg1xdWVyaWVzLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8a",
            "D3Jlc3BvbnNlcy5wcm90byJNCg1Ub3JpaVJlc3BvbnNlEisKCXR4X3N0YXR1",
            "cxgBIAEoDjIYLmlyb2hhLnByb3RvY29sLlR4U3RhdHVzEg8KB3R4X2hhc2gY",
            "AiABKAwiIgoPVHhTdGF0dXNSZXF1ZXN0Eg8KB3R4X2hhc2gYASABKAwiUQoZ",
            "QXBwbHlHZW5lc2lzQmxvY2tSZXNwb25zZRI0CgdhcHBsaWVkGAEgASgOMiMu",
            "aXJvaGEucHJvdG9jb2wuR2VuZXNpc0Jsb2NrQXBwbGllZCrAAQoIVHhTdGF0",
            "dXMSHwobU1RBVEVMRVNTX1ZBTElEQVRJT05fRkFJTEVEEAASIAocU1RBVEVM",
            "RVNTX1ZBTElEQVRJT05fU1VDQ0VTUxABEh4KGlNUQVRFRlVMX1ZBTElEQVRJ",
            "T05fRkFJTEVEEAISHwobU1RBVEVGVUxfVkFMSURBVElPTl9TVUNDRVNTEAMS",
            "DQoJQ09NTUlUVEVEEAQSDwoLSU5fUFJPR1JFU1MQBRIQCgxOT1RfUkVDRUlW",
            "RUQQBio7ChNHZW5lc2lzQmxvY2tBcHBsaWVkEhEKDUFQUExZX0ZBSUxVUkUQ",
            "ABIRCg1BUFBMWV9TVUNDRVNTEAEymAEKDkNvbW1hbmRTZXJ2aWNlEjwKBVRv",
            "cmlpEhsuaXJvaGEucHJvdG9jb2wuVHJhbnNhY3Rpb24aFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkSSAoGU3RhdHVzEh8uaXJvaGEucHJvdG9jb2wuVHhTdGF0",
            "dXNSZXF1ZXN0Gh0uaXJvaGEucHJvdG9jb2wuVG9yaWlSZXNwb25zZTJMCgxR",
            "dWVyeVNlcnZpY2USPAoERmluZBIVLmlyb2hhLnByb3RvY29sLlF1ZXJ5Gh0u",
            "aXJvaGEucHJvdG9jb2wuUXVlcnlSZXNwb25zZTKzAQoTR2VuZXNpc0Jsb2Nr",
            "U2VydmljZRJUChBTZW5kR2VuZXNpc0Jsb2NrEhUuaXJvaGEucHJvdG9jb2wu",
            "QmxvY2saKS5pcm9oYS5wcm90b2NvbC5BcHBseUdlbmVzaXNCbG9ja1Jlc3Bv",
            "bnNlEkYKFVNlbmRBYm9ydEdlbmVzaXNCbG9jaxIVLmlyb2hhLnByb3RvY29s",
            "LkJsb2NrGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Iroha.Protocol.BlockReflection.Descriptor, global::Iroha.Protocol.QueriesReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Iroha.Protocol.ResponsesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Iroha.Protocol.TxStatus), typeof(global::Iroha.Protocol.GenesisBlockApplied), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Iroha.Protocol.ToriiResponse), global::Iroha.Protocol.ToriiResponse.Parser, new[]{ "TxStatus", "TxHash" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Iroha.Protocol.TxStatusRequest), global::Iroha.Protocol.TxStatusRequest.Parser, new[]{ "TxHash" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Iroha.Protocol.ApplyGenesisBlockResponse), global::Iroha.Protocol.ApplyGenesisBlockResponse.Parser, new[]{ "Applied" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TxStatus {
    [pbr::OriginalName("STATELESS_VALIDATION_FAILED")] StatelessValidationFailed = 0,
    [pbr::OriginalName("STATELESS_VALIDATION_SUCCESS")] StatelessValidationSuccess = 1,
    [pbr::OriginalName("STATEFUL_VALIDATION_FAILED")] StatefulValidationFailed = 2,
    [pbr::OriginalName("STATEFUL_VALIDATION_SUCCESS")] StatefulValidationSuccess = 3,
    [pbr::OriginalName("COMMITTED")] Committed = 4,
    [pbr::OriginalName("IN_PROGRESS")] InProgress = 5,
    [pbr::OriginalName("NOT_RECEIVED")] NotReceived = 6,
  }

  public enum GenesisBlockApplied {
    [pbr::OriginalName("APPLY_FAILURE")] ApplyFailure = 0,
    [pbr::OriginalName("APPLY_SUCCESS")] ApplySuccess = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ToriiResponse : pb::IMessage<ToriiResponse> {
    private static readonly pb::MessageParser<ToriiResponse> _parser = new pb::MessageParser<ToriiResponse>(() => new ToriiResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ToriiResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Iroha.Protocol.EndpointReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToriiResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToriiResponse(ToriiResponse other) : this() {
      txStatus_ = other.txStatus_;
      txHash_ = other.txHash_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToriiResponse Clone() {
      return new ToriiResponse(this);
    }

    /// <summary>Field number for the "tx_status" field.</summary>
    public const int TxStatusFieldNumber = 1;
    private global::Iroha.Protocol.TxStatus txStatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Iroha.Protocol.TxStatus TxStatus {
      get { return txStatus_; }
      set {
        txStatus_ = value;
      }
    }

    /// <summary>Field number for the "tx_hash" field.</summary>
    public const int TxHashFieldNumber = 2;
    private pb::ByteString txHash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString TxHash {
      get { return txHash_; }
      set {
        txHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ToriiResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ToriiResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TxStatus != other.TxStatus) return false;
      if (TxHash != other.TxHash) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TxStatus != 0) hash ^= TxStatus.GetHashCode();
      if (TxHash.Length != 0) hash ^= TxHash.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TxStatus != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TxStatus);
      }
      if (TxHash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(TxHash);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TxStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TxStatus);
      }
      if (TxHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TxHash);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ToriiResponse other) {
      if (other == null) {
        return;
      }
      if (other.TxStatus != 0) {
        TxStatus = other.TxStatus;
      }
      if (other.TxHash.Length != 0) {
        TxHash = other.TxHash;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            txStatus_ = (global::Iroha.Protocol.TxStatus) input.ReadEnum();
            break;
          }
          case 18: {
            TxHash = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TxStatusRequest : pb::IMessage<TxStatusRequest> {
    private static readonly pb::MessageParser<TxStatusRequest> _parser = new pb::MessageParser<TxStatusRequest>(() => new TxStatusRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TxStatusRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Iroha.Protocol.EndpointReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TxStatusRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TxStatusRequest(TxStatusRequest other) : this() {
      txHash_ = other.txHash_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TxStatusRequest Clone() {
      return new TxStatusRequest(this);
    }

    /// <summary>Field number for the "tx_hash" field.</summary>
    public const int TxHashFieldNumber = 1;
    private pb::ByteString txHash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString TxHash {
      get { return txHash_; }
      set {
        txHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TxStatusRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TxStatusRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TxHash != other.TxHash) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TxHash.Length != 0) hash ^= TxHash.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TxHash.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(TxHash);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TxHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TxHash);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TxStatusRequest other) {
      if (other == null) {
        return;
      }
      if (other.TxHash.Length != 0) {
        TxHash = other.TxHash;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            TxHash = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ApplyGenesisBlockResponse : pb::IMessage<ApplyGenesisBlockResponse> {
    private static readonly pb::MessageParser<ApplyGenesisBlockResponse> _parser = new pb::MessageParser<ApplyGenesisBlockResponse>(() => new ApplyGenesisBlockResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApplyGenesisBlockResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Iroha.Protocol.EndpointReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplyGenesisBlockResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplyGenesisBlockResponse(ApplyGenesisBlockResponse other) : this() {
      applied_ = other.applied_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplyGenesisBlockResponse Clone() {
      return new ApplyGenesisBlockResponse(this);
    }

    /// <summary>Field number for the "applied" field.</summary>
    public const int AppliedFieldNumber = 1;
    private global::Iroha.Protocol.GenesisBlockApplied applied_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Iroha.Protocol.GenesisBlockApplied Applied {
      get { return applied_; }
      set {
        applied_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApplyGenesisBlockResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApplyGenesisBlockResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Applied != other.Applied) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Applied != 0) hash ^= Applied.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Applied != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Applied);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Applied != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Applied);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApplyGenesisBlockResponse other) {
      if (other == null) {
        return;
      }
      if (other.Applied != 0) {
        Applied = other.Applied;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            applied_ = (global::Iroha.Protocol.GenesisBlockApplied) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
